added party id to eq payload
ONSdigital/ras-frontstage pull request #736
Opened 2021-05-24 12:43 UTC by anwilkie

# What and why?
The party ID needed to be added to the EQ payload to facilitate the "help" link.

# Trello
[Card](https://trello.com/c/cENWYFNf)

2021-05-25 09:40 UTC, insacuri requested changes

2021-05-25 09:40 UTC, insacuri commented on tests/integration/test_generate_eq.py
> +        mock_request.get(url_get_case, json=case)
This whole block of mock requests can be replaced with just these 4:

```python
mock_request.get(url_get_collection_exercise, json=collection_exercise)
mock_request.get(url_get_collection_exercise_events, json=collection_exercise_events)
mock_request.get(url_get_business_party, json=business_party)
mock_request.get(url_get_ci, json=collection_instrument_eq)
```
You shouldn't just copy a bunch of them from another test >_<  If you look at what the `create_payload` function is doing, you can see it's only doing calls to collection exercise, party and collection instrument, so you don't need the case mocks as they'll never be called.

2021-06-01 14:57 UTC, insacuri approved these changes

2021-06-10 07:07 UTC, warrenbailey requested changes
This is really good work @anwilkie however we're now taking a different approach to this so unfortunately it is no longer needed. Please discuss with @insacuri and then close this PR.

2021-06-10 11:29 UTC, insacuri commented
Closing as it's not needed anymore

2021-06-10 11:29 UTC, closed without merging