Help url stuff
ONSdigital/ras-frontstage pull request #741
Opened 2021-06-17 08:19 UTC by anwilkie

# What and why?

The help pages needed to be exposed to the EQ payload by using a `survey_ref` and `ru_ref` in the URLs. These variables are, in turn, used to retrieve the business ID and survey short name.

# How to test?

(TBD)

# Trello

[Card](https://trello.com/c/cENWYFNf)

2021-06-25 08:09 UTC, anwilkie commented
/deploy wilkia

2021-06-28 09:07 UTC, warrenbailey commented
/deploy baileyw

2021-06-28 09:47 UTC, warrenbailey reviewed
I think the issue you have for all of these urls  is that you've changed the get_send_help_message_page function to accept survey survey ref and ru ref, but when it's being called via url_for its still trying to use the short name and business ids as well as the new parameters, so it's failing to find the function and just saying on the same page.

Either you have to update all the url_for calls in the templates and remove short_name and business_id or add an additional url_for function for getting the help pages by survey ref and ru ref and leave everything else as is.

2021-06-30 09:23 UTC, mfcrocker commented
/deploy crockerm

2021-06-30 09:39 UTC, mfcrocker commented
Generally looks good, but your breadcrumbs aren't working and are returning our good friend the 500 screen. It's likely you need to update the URL for them

2021-06-30 09:39 UTC, mfcrocker requested changes
Generally LGTM, but from testing your breadcrumbs are returning 500s in places. You probably need to update the URL there.

2021-07-01 11:49 UTC, mfcrocker commented
/deploy crockerm

2021-07-01 11:53 UTC, mfcrocker approved these changes
LGTM

2021-07-02 10:09 UTC, mfcrocker approved these changes

2021-07-02 10:09 UTC, mfcrocker commented on _infra/helm/frontstage/Chart.yaml
> +appVersion: 2.2.100
```suggestion
appVersion: 2.3.0
```

This isn't your fault or anything, I just think if we're getting to patch number 100 it's probably time to roll that sucker over 🤣

2021-07-02 12:17 UTC, merged