changed logging statements and added active iac check
ONSdigital/ras-frontstage pull request #806
Opened 2022-01-21 10:51 UTC by anwilkie

# What and why?
There have been errors and bugs relating to enrolment codes in frontstage recently. In prod on mobile devices, the same enrolment codes have been used more than once, and Safari browsers sometimes error when entering an enrolment code. The cause of these issues is unknown at the moment, but these amended log statements might shed light on the issue. In addition, prior to now, the code for checking the IAC when adding a new survey would explicitly check for the active state, yet for some reason, this check was missing when creating a new account. This PR makes the code more symmetrical between the two processes. I'm not sure if this will fix the bug with enrolment codes being able to be used more than once, but having an extra check in place won't hurt.

# Trello
[Card](https://trello.com/c/sNchCVKZ)

2022-01-25 09:52 UTC, JacobHarrisonONS approved these changes

2022-01-25 10:09 UTC, creativeappdevamit requested changes
Looks ok to me. Can we add some more logging along side cryptograher?

2022-01-25 10:09 UTC, creativeappdevamit commented on frontstage/views/surveys/add_survey.py
> +        logger.info("Successful enrolment code submitted when attempting to add survey", enrolment_code=enrolment_code)
I don't think its successfully submitted
Can you add a log line to suggest that all validation has been completed and now we will decrypt 
another on that the decoding was done sucessfully
and once we actually save the info in db then we suggest it has been sumitted.

2022-01-27 09:51 UTC, creativeappdevamit approved these changes
Fix merge conflict

2022-01-27 11:32 UTC, merged