Apply restrictions to forgotten password journey.
ONSdigital/ras-frontstage pull request #838
Opened 2022-04-06 08:47 UTC by arroyoAle

# What and why?
Adding restrictions to amount of password reset attempts
# How to test?

# Trello

2022-04-12 12:03 UTC, creativeappdevamit approved these changes

2022-04-21 09:40 UTC, anwilkie commented
/deploy wilkia

2022-04-21 11:06 UTC, insacuri requested changes
A few changes but overall it looks good ^^

2022-04-22 09:00 UTC, insacuri commented on frontstage/controllers/party_controller.py
>      url = f"{app.config['PARTY_URL']}/party-api/v1/respondents/{party_id}/password-verification-tokens"
wasn't `tokens` the deprecated one?  this (and all the other `-tokens` urls) should be changed to the new one to make less work for us later on

2022-04-22 10:54 UTC, insacuri approved these changes

2022-04-22 10:58 UTC, merged