Update to Design System v70
ONSdigital/ras-frontstage pull request #962
Opened 2024-03-05 15:02 UTC by mfcrocker

# What and why?
We keep up to date with design system releases.

# How to test?
General smoke test paying attention to any janky CSS. Pay special attention to the Secure Message thread list

# Jira
RAS-1093

2024-03-05 16:37 UTC, LJBabbage requested changes
This one needs to go back to design system, they have their piping in the wrong order and they haven't documented the component

2024-03-19 14:02 UTC, mfcrocker commented
/deploy crockers

2024-03-19 15:38 UTC, LJBabbage requested changes
It looks like you have missed this change https://github.com/ONSdigital/design-system/pull/3047

2024-03-19 15:38 UTC, LJBabbage commented on frontstage/templates/secure-messages/conversation-list.html
> +                "headingLevel": 2
You shouldn't need to provide this anymore

2024-03-20 09:33 UTC, anwilkie commented
/deploy wilkia

2024-03-20 12:46 UTC, anwilkie requested changes
<img width="1107" alt="Screenshot 2024-03-20 at 09 51 18" src="https://github.com/ONSdigital/ras-frontstage/assets/47449873/8af1c778-568b-4ddb-8a53-58367e2ca9f9">

Tests run okay, but when I was looking around frontstage, I noticed that the formatting of the account details page has gotten messed up, and the `Name:`, `Email address:`, and `Phone number:` fields should be bolded, but aren't.

2024-03-26 09:24 UTC, anwilkie commented
/deploy wilkia

2024-03-26 09:33 UTC, anwilkie approved these changes
The issues I highlighted have been resolved. Looks good to me.

2024-03-26 12:50 UTC, merged