Remove EQ version
ONSdigital/ras-frontstage pull request #979
Opened 2024-06-03 11:14 UTC by mfcrocker

# What and why?
EQ v2 has been dead for some time, this removes the concept of a particular version

# How to test?
General smoke test around surveys

# Jira
RAS-1144

2024-06-10 10:40 UTC, LJBabbage requested changes

2024-06-10 10:40 UTC, LJBabbage commented on frontstage/common/eq_payload.py
> -            "version": "v2",
We don't want to remove the payload version, this will break eQ

2024-06-10 14:38 UTC, LJBabbage requested changes

2024-06-10 14:38 UTC, LJBabbage commented on tests/integration/test_generate_eq.py
> -    "version": "v2",
Needs restoring as well

2024-06-11 10:46 UTC, arroyoAle approved these changes
Tests run fine and there are no actual functional changes needed

2024-06-12 12:48 UTC, merged